### PR TITLE
Added Contact Us section with its functionality

### PR DESCRIPTION
**Pull request by K-jais**
Added contact us functionality and the social media icons in that section. Now a user can request anything from the admin using this contact us and the response will be sent to the admin in the form of mail. 

It's working video,

https://user-images.githubusercontent.com/75881393/125206513-534d7b00-e2a5-11eb-9a0c-717f106fb1a5.mp4

### CODE REVIEW

**Comment by K-jais** [comment]
Please @akshitadixit review this PR before merging any other PR.

**Comment by K-jais** [comment]
It resolves issue #47

**Comment by akshitadixit** [comment]
Hey @K-jais that looks good! Could you please remove the phone number from there? Also probably you should go ahead and create an actual gmail account for structurex so the form can remain functional even after you :)

**Comment by K-jais** [comment]
Please @akshitadixit  look into this now
I have made its account Email: structurexcodes@gmail.com        Password: structurex1234
I have also removed the mobile number. 
Please review it now.

**Comment by K-jais** [comment]
- @akshitadixit Please look into this

**Comment by akshitadixit** [comment]
@K-jais please resolve the conflicts. Also send the password n mail on slack and kindly delete that comment.

**Pull request closed without merging**
